version: 2

updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Tbilisi"
    open-pull-requests-limit: 5
    assignees:
      - "edelwud/platform-team"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "go"
    ignore:
      # Ignore patch updates for stable dependencies
      - dependency-name: "github.com/sirupsen/logrus"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "gopkg.in/yaml.v3"
        update-types: ["version-update:semver-patch"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Tbilisi"
    open-pull-requests-limit: 3
    assignees:
      - "edelwud/platform-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Tbilisi"
    open-pull-requests-limit: 2
    assignees:
      - "edelwud/platform-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
