server:
  address: "127.0.0.1:8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

upstream:
  url: "http://localhost:9090"
  timeout: "30s"
  max_retries: 3
  retry_delay: "1s"
  tenant_header: "X-Prometheus-Tenant"
  tenant_label: "vm_account_id"

auth:
  type: "jwt"
  # For RS256 with JWKS (e.g., Keycloak, Auth0)
  jwks_url: "https://your-auth-server.com/.well-known/jwks.json"
  jwt_algorithm: "RS256"
  validate_audience: false
  validate_issuer: false
  required_issuer: "https://your-auth-server.com"
  token_ttl: "1h"
  cache_ttl: "5m"
  user_groups_claim: "groups"

tenant_mappings:
  - groups: ["admin"]
    tenants: ["*"]
    read_only: false
  - groups: ["developers"]
    tenants: ["dev", "test"]
    read_only: false
  - groups: ["viewers"]
    tenants: ["dev", "test", "prod"]
    read_only: true

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info"
  format: "json"