# Example configuration for secure multi-tenant filtering
# This configuration demonstrates the new OR-based tenant filtering strategy
# that prevents cross-tenant data leakage in VictoriaMetrics

server:
  address: "0.0.0.0:8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

upstream:
  url: "http://victoriametrics:8428"
  timeout: "30s"
  max_retries: 3
  retry_delay: "1s"
  
  # VictoriaMetrics multi-tenancy configuration
  tenant_label: "vm_account_id"
  project_label: "vm_project_id"
  use_project_id: true
  
  # NEW: Tenant filtering strategy configuration
  tenant_filter:
    # SECURE: Use OR-based filtering to prevent cartesian product security issues
    # For users with multiple tenants like:
    # - {account_id: 1000, project_id: ".*"}
    # - {account_id: 2000, project_id: "20"}
    #
    # UNSAFE regex strategy would create: {vm_account_id=~"(1000|2000)",vm_project_id=~"(.*|20)"}
    # This allows access to account 2000 + project .* (SECURITY BREACH!)
    #
    # SAFE OR strategy creates: {vm_account_id="1000"} or {vm_account_id="2000",vm_project_id="20"}
    # This ensures perfect tenant isolation
    strategy: "or_conditions"  # Options: "regex" (legacy, unsafe), "or_conditions" (secure)

auth:
  type: "jwt"
  jwks_url: "https://your-auth-provider.com/.well-known/jwks.json"
  jwt_algorithm: "RS256"
  validate_audience: false
  validate_issuer: false
  token_ttl: "1h"
  cache_ttl: "5m"
  user_groups_claim: "groups"

# Tenant mappings - map OAuth groups to VictoriaMetrics tenants
tenant_mappings:
  - groups: ["platform-team"]
    vm_tenants:
      - account_id: "1000"
        project_id: ".*"  # Full access to account 1000
      - account_id: "2000" 
        project_id: ".*"  # Full access to account 2000
    read_only: false

  - groups: ["dev-team-frontend"]
    vm_tenants:
      - account_id: "1000"
        project_id: "frontend"  # Limited to frontend project
    read_only: false

  - groups: ["dev-team-backend"]
    vm_tenants:
      - account_id: "1000"
        project_id: "backend"  # Limited to backend project
    read_only: false
    
  - groups: ["security-audit"]
    vm_tenants:
      - account_id: "1000"
        project_id: ".*"  # Full read access for auditing
      - account_id: "2000"
        project_id: "20"   # Limited project access
    read_only: true

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info"
  format: "json"