server:
  address: ":8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

upstream:
  url: "http://victoriametrics:8428"
  timeout: "30s"
  tenant_label: "vm_account_id"
  project_label: "vm_project_id"
  use_project_id: false
  tenant_header: "X-Tenant-ID"

auth:
  jwt_secret: "your-secret-key-here"
  jwt_algorithm: "HS256"
  cache_ttl: "5m"

logging:
  level: "info"
  format: "json"

# Enable Prometheus metrics
metrics:
  enabled: true

# Example tenant mappings
tenant_maps:
  - user_claim: "sub"
    user_value: "user@example.com"
    vm_tenants:
      - account_id: "1000"
        project_id: "production"
      - account_id: "1001"
        project_id: "staging"