server:
  address: "0.0.0.0:8080"
  timeouts:
    readTimeout: "30s"
    writeTimeout: "30s"
    idleTimeout: "60s"

upstream:
  url: "https://vmselect.example.com"  # VictoriaMetrics single-node
  timeout: "30s"
  retry:
    maxRetries: 3
    retryDelay: "1s"

auth:
  jwt:
    algorithm: "RS256"
    jwksUrl: "https://keycloak.example.com/realms/staff/protocol/openid-connect/certs"
    # secret: "your-secret-key"  # Alternative to JWKS for HS256
    validation:
      validateAudience: false
      validateIssuer: true
      requiredIssuer: "https://keycloak.example.com/realms/staff"
      requiredAudience: []
    claims:
      userGroupsClaim: "groups"
    tokenTtl: "1h"
    cacheTtl: "5m"

tenantMapping:
  - groups: ["developers"]
    vmTenants:  # VictoriaMetrics specific
      - accountId: "2000"
        # No projectId means access to all projects in account
    readOnly: false

tenantFilter:
  strategy: "orConditions"  # Secure OR-based filtering (recommended)  
  labels:
    # VictoriaMetrics multi-tenancy configuration
    accountLabel: "vm_account_id"  # Account ID label
    projectLabel: "vm_project_id"  # Project ID label (optional)
    useProjectId: true  # Enable account:project filtering

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info"  # More verbose for testing
  format: "json"
