server:
  address: "127.0.0.1:8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

upstream:
  url: "http://localhost:9090"
  timeout: "30s"
  max_retries: 3
  retry_delay: "1s"
  tenant_header: "X-Prometheus-Tenant"
  tenant_label: "vm_account_id"

auth:
  type: "jwt"
  jwt_secret: "test-secret-key"
  jwt_algorithm: "HS256"
  validate_audience: false
  validate_issuer: false
  token_ttl: "1h"
  cache_ttl: "5m"
  user_groups_claim: "groups"

tenant_mappings:
  - groups: ["admin"]
    tenants: ["*"]
    read_only: false
  - groups: ["developers"]
    tenants: ["dev", "test"]
    read_only: false
  - groups: ["viewers"]
    tenants: ["dev", "test", "prod"]
    read_only: true

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info"
  format: "json"