server:
  address: "0.0.0.0:8090"

backends:
  - url: "http://localhost:8428"
    weight: 1

loadBalancing:
  strategy: "round-robin"

timeout: "30s"

# NO Raft - только memberlist discovery тестирование
stateStorage:
  type: "local"

# Auto-discovery configuration - Node 1
discovery:
  enabled: true
  providers: ["mdns", "static"]
  interval: "10s"
  mdns:
    serviceName: "_vm-proxy-auth._tcp"
    domain: "local."
    hostname: "node-1-test"
    port: 7946
  static:
    peers: []

# Memberlist configuration - Node 1
memberlist:
  bindAddress: "127.0.0.1"
  bindPort: 7946
  advertiseAddress: "127.0.0.1"
  advertisePort: 7946
  gossipInterval: "200ms"
  gossipNodes: 3
  probeInterval: "1s"
  probeTimeout: "500ms"
  metadata:
    node_name: "node-1-test"
    role: "peer"
    environment: "test"

auth:
  jwt:
    algorithm: "HS256"
    secret: "test-secret-key-at-least-32-chars-long-for-hs256"
    tokenTtl: "1h"
    validation:
      validateAudience: false
      validateIssuer: false

tenantMapping:
  - groups: ["admin"]
    vmTenants:
      - accountId: "0"
    readOnly: false

tenantFilter:
  strategy: "orConditions"
  labels:
    accountLabel: "vm_account_id"
    projectLabel: "vm_project_id"
    useProjectId: false

logging:
  level: "debug"
  format: "pretty"