server:
  address: "0.0.0.0:8080"
  timeouts:
    readTimeout: "30s"
    writeTimeout: "30s"
    idleTimeout: "60s"

upstream:
  url: "https://vmselect.example.com"
  timeout: "30s"
  retry:
    maxRetries: 3
    retryDelay: "1s"

auth:
  jwt:
    # For HS256 with shared secret
    algorithm: "HS256"
    secret: "your-256-bit-secret-key-here-must-be-long-enough"
    validation:
      validateAudience: false
      validateIssuer: true
      requiredIssuer: "https://your-service.com"
      requiredAudience: ["vm-proxy-auth"]
    claims:
      userGroupsClaim: "groups"
    tokenTtl: "1h"
    cacheTtl: "5m"

tenantMapping:
  - groups: ["admin"]
    vmTenants:
      - accountId: "1000"
        # No projectId means access to all projects
    readOnly: false
    
  - groups: ["developers"]
    vmTenants:
      - accountId: "2000"
        projectId: "10"
    readOnly: false
    
  - groups: ["viewers"]
    vmTenants:
      - accountId: "2000"
        projectId: "10"
    readOnly: true

tenantFilter:
  strategy: "orConditions"
  labels:
    accountLabel: "vm_account_id"
    projectLabel: "vm_project_id"
    useProjectId: true

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info"
  format: "json"
