server:
  address: "127.0.0.1:8080"
  timeouts:
    readTimeout: "5s"
    writeTimeout: "5s"
    idleTimeout: "10s"

upstream:
  url: "http://localhost:9090"
  timeout: "5s"
  retry:
    maxRetries: 1
    retryDelay: "100ms"

auth:
  jwt:
    algorithm: "HS256"
    secret: "test-secret-key-for-development-only"
    validation:
      validateAudience: false
      validateIssuer: false
      requiredIssuer: ""
      requiredAudience: []
    claims:
      userGroupsClaim: "groups"
    tokenTtl: "15m"
    cacheTtl: "1m"

tenantMapping:
  - groups: ["test-users"]
    vmTenants:
      - accountId: "1000"
        projectId: "test"
    readOnly: false

tenantFilter:
  strategy: "orConditions"
  labels:
    accountLabel: "vm_account_id"
    projectLabel: "vm_project_id"
    useProjectId: true

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "debug"  # Verbose for testing
  format: "text"  # Easier to read during development
