server:
  address: "0.0.0.0:8080"
  timeouts:
    readTimeout: "30s"
    writeTimeout: "30s"  
    idleTimeout: "60s"

upstream:
  url: "https://vmselect.example.com"
  timeout: "30s"
  retry:
    maxRetries: 3
    retryDelay: "1s"

auth:
  jwt:
    algorithm: "RS256"
    jwksUrl: "https://keycloak.example.com/realms/staff/protocol/openid-connect/certs"
    # secret: "your-secret-key"  # Alternative to JWKS for HS256
    validation:
      validateAudience: false
      validateIssuer: true
      requiredIssuer: "https://keycloak.example.com/realms/staff"
      requiredAudience: []
    claims:
      userGroupsClaim: "groups"
    tokenTtl: "1h"
    cacheTtl: "5m"

tenantMapping:
  - groups: ["developers", "platform-admin"]
    vmTenants:
      - accountId: "1000"
        projectId: "10"
    readOnly: false
    
  - groups: ["team-alpha", "dev-alpha"]
    vmTenants:
      - accountId: "2000"
        projectId: "20"
      - accountId: "2000"
        projectId: "21"
    readOnly: false
    
  - groups: ["team-beta"]
    vmTenants:
      - accountId: "3000"
        # No projectId means access to all projects in account
    readOnly: false
    
  - groups: ["readonly-users", "auditors"]
    vmTenants:
      - accountId: "1000"
        projectId: "10"
      - accountId: "2000"
        projectId: "20"
    readOnly: true

tenantFilter:
  strategy: "orConditions"  # Secure OR-based filtering (recommended)
  # strategy: "regex"       # Legacy regex filtering (deprecated)
  labels:
    accountLabel: "vm_account_id"
    projectLabel: "vm_project_id"
    useProjectId: true

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info"
  format: "json"
