server:
  address: "0.0.0.0:8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

upstream:
  url: "https://vmselect.example.com" # VictoriaMetrics single-node
  timeout: "30s"
  max_retries: 3
  retry_delay: "1s"
  tenant_header: "X-Prometheus-Tenant"
  # VictoriaMetrics multi-tenancy configuration
  tenant_label: "vm_account_id" # Account ID label
  project_label: "vm_project_id" # Project ID label (optional)
  use_project_id: true # Enable account:project filtering

auth:
  type: "jwt"
  jwks_url: "https://keycloak.example.com/realms/staff/protocol/openid-connect/certs"
  # jwt_secret: "your-secret-key"  # Alternative to JWKS
  jwt_algorithm: "RS256"
  validate_audience: false
  validate_issuer: true
  required_issuer: "https://keycloak.example.com/realms/staff"
  required_audience: []
  token_ttl: "1h"
  cache_ttl: "5m"
  user_groups_claim: "groups"

tenant_mappings:
  - groups: ["developers"]
    vm_tenants: # VictoriaMetrics specific
      - account_id: "2000"
    read_only: false

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info" # More verbose for testing
  format: "json"
