server:
  address: "0.0.0.0:8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

upstream:
  url: "https://vmselect.example.com"
  timeout: "30s"
  max_retries: 3
  retry_delay: "1s"
  tenant_header: "X-Prometheus-Tenant"
  tenant_label: "tenant_id"

auth:
  type: "jwt"
  jwks_url: "https://keycloak.example.com/realms/staff/protocol/openid-connect/certs"
  # jwt_secret: "your-secret-key"  # Alternative to JWKS
  jwt_algorithm: "RS256"
  validate_audience: false
  validate_issuer: true
  required_issuer: "https://keycloak.example.com/realms/staff"
  required_audience: []
  token_ttl: "1h"
  cache_ttl: "5m"
  user_groups_claim: "groups"

tenant_mappings:
  - groups: ["developers", "platform-admin"]
    tenants: ["2000"] # Access to all tenants
    read_only: false

  - groups: ["team-alpha", "dev-alpha"]
    tenants: ["alpha", "alpha-dev", "alpha-staging"]
    read_only: false

  - groups: ["team-beta"]
    tenants: ["beta", "beta-prod"]
    read_only: false

  - groups: ["readonly-users", "auditors"]
    tenants: ["alpha", "beta"]
    read_only: true

metrics:
  enabled: true
  path: "/metrics"

logging:
  level: "info"
  format: "json"
