name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

env:
  GO_VERSION: "1.24.4"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          else
            VERSION="dev-$(git rev-parse --short HEAD)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Get commits since last tag
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
            if [[ -n "$PREVIOUS_TAG" ]]; then
              CHANGELOG=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD)
            else
              CHANGELOG=$(git log --pretty=format:"- %s" HEAD~10..HEAD)
            fi
          else
            CHANGELOG="Development build"
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Changes
            ${{ steps.changelog.outputs.changelog }}

            ## Installation

            ### Binary
            Download the appropriate binary for your platform below.

            ### Docker
            ```bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.version }}
            ```

            ### Go Install
            ```bash
            go install github.com/edelwud/vm-proxy-auth/cmd/gateway@${{ github.ref_name }}
            ```
          draft: false
          prerelease: ${{ contains(github.ref_name, '-') }}

  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        include:
          # Linux
          - os: linux
            arch: amd64
            goos: linux
            goarch: amd64
          - os: linux
            arch: arm64
            goos: linux
            goarch: arm64
          - os: linux
            arch: arm
            goos: linux
            goarch: arm
            goarm: 7
          # macOS
          - os: darwin
            arch: amd64
            goos: darwin
            goarch: amd64
          - os: darwin
            arch: arm64
            goos: darwin
            goarch: arm64
          # Windows
          - os: windows
            arch: amd64
            goos: windows
            goarch: amd64
            ext: .exe
          - os: windows
            arch: arm64
            goos: windows
            goarch: arm64
            ext: .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
          CGO_ENABLED: 0
        run: |
          VERSION=${{ needs.create-release.outputs.version }}
          BUILD_TIME=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          GIT_COMMIT=$(git rev-parse HEAD)

          BINARY_NAME="vm-proxy-auth-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}"

          go build \
            -ldflags "-s -w -X main.version=$VERSION -X main.buildTime=$BUILD_TIME -X main.gitCommit=$GIT_COMMIT" \
            -o "$BINARY_NAME" \
            ./cmd/gateway

          # Create checksums
          if command -v sha256sum &> /dev/null; then
            sha256sum "$BINARY_NAME" > "$BINARY_NAME.sha256"
          else
            shasum -a 256 "$BINARY_NAME" > "$BINARY_NAME.sha256"
          fi

      - name: Upload binary to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./vm-proxy-auth-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          asset_name: vm-proxy-auth-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
          asset_content_type: application/octet-stream

      - name: Upload checksum to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./vm-proxy-auth-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}.sha256
          asset_name: vm-proxy-auth-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}.sha256
          asset_content_type: text/plain

  build-docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: create-release

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Tag with version for releases
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable={{is_default_branch}}
            # Tag with branch name for non-main branches
            type=ref,event=branch,enable={{is_default_branch}}
            # Tag with PR number for pull requests
            type=ref,event=pr
            # Tag with git short SHA
            type=sha,prefix={{branch}}-,enable={{is_default_branch}}
            # Latest tag for main branch releases
            type=raw,value=latest,enable={{is_default_branch}}
            # Edge tag for main branch
            type=edge,branch=main
          labels: |
            org.opencontainers.image.title=VM Proxy Auth
            org.opencontainers.image.description=VictoriaMetrics Proxy with Authentication and Multi-tenant Support
            org.opencontainers.image.url=https://github.com/edelwud/vm-proxy-auth
            org.opencontainers.image.source=https://github.com/edelwud/vm-proxy-auth
            org.opencontainers.image.vendor=edelwud
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.documentation=https://github.com/edelwud/vm-proxy-auth/blob/main/README.md
          annotations: |
            org.opencontainers.image.title=VM Proxy Auth
            org.opencontainers.image.description=VictoriaMetrics Proxy with Authentication and Multi-tenant Support
            org.opencontainers.image.url=https://github.com/edelwud/vm-proxy-auth
            org.opencontainers.image.source=https://github.com/edelwud/vm-proxy-auth
            org.opencontainers.image.vendor=edelwud
            org.opencontainers.image.licenses=MIT

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          build-args: |
            VERSION=${{ needs.create-release.outputs.version }}
            BUILD_TIME=${{ github.event.head_commit.timestamp || github.event.repository.updated_at }}
            GIT_COMMIT=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true
          provenance: true

